### ISSUE TITLE
If Owner Hides Name They Lose All Control

### ISSUE THREAD

**Issue by RobertMCForster** [EthereumCommonwealth/DexNS#1]
Since any of the editing functions (including hiding the owner name) have the only_name_owner modifier and that modifier requires the contract to be able to get ownerOf, if an owner hides their ownership frontend will throw on any other edit they try to make. 

To fix this the getName function can have an exception to hideOwner if the caller is frontend.

**Comment by Dexaran** [comment]
Fixed with https://github.com/EthereumCommonwealth/DexNS/commit/04eacda82298418e02e37aeabd23c3761ee01b7e

**Comment by Dexaran** [comment]
This bug was evaluated as point 2 of the bug bounty: **security vulnerabilities and bugs, that could not be directly exploited but can affect contracts in some specific circumstances.**

I'm ready to reward you with $2000 in ETC or any other crypto that I can buy if you don't like ETC. Please, provide your address here.

**Comment by RobertMCForster** [comment]
Fantastic, my ETC address is: 0x490be2bd4d8c7bdef4f8136b9c6a6f6d0c8a0477

**Comment by Dexaran** [comment]
Let's wait for markets to stabilize. I'd like to evaluate the reward at Nov 30, 2017 23:00 CEST by Poloniex ETCUSDT rate and then I will send it to the given address.

**Comment by Dexaran** [comment]
Sent: https://gastracker.io/tx/0x36b7b0dc282e0c267427ac4d56c792147a4f49fd661402e03f99b543503ff85a

**Comment by RobertMCForster** [comment]
Fantastic, thanks again!
