### ISSUE TITLE
Functions - naming convention

### ISSUE THREAD

**Issue by pauliax** [EthereumCommonwealth/DexNS#11]
Some functions have names like
assignName, unassignName, isContract, debugCall, etc
others:
extend_Name_Binding_Time, change_Storage_Address, change_Owner

Consider refactoring the names to be consistent. I would suggest keeping a Solidity standard naming convention, thus refactoring every function to have such style: myFunctionName.

Another minor suggestion:
    /** 
    * @dev Debugging function that changes the DexNS owner address.
    *
    * @param _newOwner  Address to be considered a new DexNS owner.
    */
    function change_Owner(address _newOwner) only_owner
    {
        owner = _newOwner;
    }

the comment says "debugging function" but the function itself doesn't have a modifier only_debug. Also, consider emitting event OwnershipTransferred to enrich the user experience.

**Comment by Dexaran** [comment]
The main idea of this approach is to make two versions of contract ABI. One version with full names for developers and another version with only those functions that a normal user can call to manage the content of the name without the help of third-party interfaces. 

Users do not need to see debugging functions (which only the owner can call) and some other functions that provide advanced functionality. That's why I decided to make a shortened version of ABI to publish it for normal users.

Extended ABI will have all functions. Shortened ABI will not have `underline_Styled_Functions`. That's why two different function naming styles were used.

**Comment by pauliax** [comment]
@Dexaran I see your point. Thanks for the informative explanation.
