### ISSUE TITLE
Throw is deprecated

### ISSUE THREAD

**Issue by pauliax** [EthereumCommonwealth/DexNS#9]
if(name_assignation[sha256(assignation[_destination])] != 0x0) throw;

"Throw" is now deprecated in Solidity in favour of "revert()", "require()" and "assert()". So please replace 
if (!condition) {throw;} 
to
require(condition);
because "require" automatically throws if the condition is not met.

**Comment by Dexaran** [comment]
The difference between `throw` and `revert()` is that `revert()` is trying to execute an opcode that does not exist (it is planned to make a newer implementation that will not burn the remaining tx gas). `throw` is burning the gas. Both cause transaction to fail: `revert` because of `Bad instruction` error and `throw` because of `Out of gas` error. It doesn't make any difference to me.

As for `require(condition)`, I would say that

`if(!condition) throw;` is intuitively clear for any developer, while `require(condition);` is not that intuitively clear (if you're not a JS dev of course) and requires a developer to learn about how the `require` works in Ethereum.

**Comment by Sanghren** [comment]
As per official doc (see : http://solidity.readthedocs.io/en/develop/control-structures.html#error-handling-assert-require-revert-and-exceptions) `throw` is deprecated since **0.4.13** and will be removed in the future . So  better to be future proof and use the `revert()` or `require()` and avoid bad surprises ;) 

Personally I would use  `require()` since you are validating an input of your function . (still mentioned in official doc).

**Comment by Dexaran** [comment]
I will not use `require` because of the reasons I've mentioned earlier. I prefer to stay with the intuitively clear code. 

I can say that if the `throw` will be removed in the latest versions of the compiler then I will not re-compile the contract with any newer compiler release once the contract is deployed. As the result, throw deprecation makes no sense.
